-- Resume System core schema baseline (ZPL-3)
-- Safe to re-run: uses CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  auth_user_id VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  email VARCHAR(255) NOT NULL,
  role ENUM('super_admin','hr','interviewer','system') NOT NULL,
  status ENUM('active','disabled') NOT NULL DEFAULT 'active',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_users_auth_user_id (auth_user_id),
  UNIQUE KEY uk_users_email (email),
  KEY idx_users_role_status (role, status),
  KEY idx_users_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS candidates (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  candidate_no VARCHAR(32) NOT NULL,
  full_name VARCHAR(128) NOT NULL,
  email VARCHAR(255) NULL,
  phone VARCHAR(32) NULL,
  source_type ENUM('manual','upload','job_board','referral') NOT NULL,
  current_company VARCHAR(128) NULL,
  current_title VARCHAR(128) NULL,
  total_experience_months INT UNSIGNED NULL,
  highest_education VARCHAR(64) NULL,
  location VARCHAR(128) NULL,
  status ENUM('new','screening','interviewing','offered','hired','rejected','talent_pool') NOT NULL DEFAULT 'new',
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_candidates_candidate_no (candidate_no),
  KEY idx_candidates_status_created_at (status, created_at),
  KEY idx_candidates_email (email),
  KEY idx_candidates_phone (phone),
  KEY idx_candidates_full_name (full_name),
  KEY idx_candidates_created_by (created_by),
  KEY idx_candidates_updated_by (updated_by),
  CONSTRAINT fk_candidates_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_candidates_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS resumes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  candidate_id BIGINT UNSIGNED NOT NULL,
  version_no INT UNSIGNED NOT NULL,
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  file_name VARCHAR(255) NOT NULL,
  file_url VARCHAR(1024) NOT NULL,
  file_hash CHAR(64) NULL,
  parse_status ENUM('pending','processing','success','failed') NOT NULL DEFAULT 'pending',
  parsed_payload JSON NULL,
  parsed_at DATETIME(3) NULL,
  uploaded_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_resumes_candidate_version (candidate_id, version_no),
  KEY idx_resumes_candidate_created_at (candidate_id, created_at),
  KEY idx_resumes_file_hash (file_hash),
  KEY idx_resumes_parse_status (parse_status),
  KEY idx_resumes_is_primary (candidate_id, is_primary),
  KEY idx_resumes_uploaded_by (uploaded_by),
  CONSTRAINT fk_resumes_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id),
  CONSTRAINT fk_resumes_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS positions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  position_code VARCHAR(32) NOT NULL,
  title VARCHAR(128) NOT NULL,
  department VARCHAR(128) NULL,
  location VARCHAR(128) NULL,
  employment_type ENUM('full_time','part_time','intern','contract') NOT NULL DEFAULT 'full_time',
  jd_text MEDIUMTEXT NULL,
  status ENUM('draft','open','paused','closed') NOT NULL DEFAULT 'draft',
  headcount INT UNSIGNED NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_positions_position_code (position_code),
  KEY idx_positions_status_department (status, department),
  KEY idx_positions_title (title),
  KEY idx_positions_created_at (created_at),
  KEY idx_positions_created_by (created_by),
  KEY idx_positions_updated_by (updated_by),
  CONSTRAINT fk_positions_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_positions_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS interviews (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  interview_no VARCHAR(32) NOT NULL,
  candidate_id BIGINT UNSIGNED NOT NULL,
  position_id BIGINT UNSIGNED NOT NULL,
  round_no INT UNSIGNED NOT NULL,
  interview_type ENUM('phone','onsite','video','technical','hr') NOT NULL,
  scheduled_start_at DATETIME(3) NOT NULL,
  scheduled_end_at DATETIME(3) NOT NULL,
  timezone VARCHAR(64) NOT NULL,
  status ENUM('scheduled','confirmed','completed','cancelled','rescheduled','no_show') NOT NULL DEFAULT 'scheduled',
  meeting_provider VARCHAR(32) NULL,
  meeting_url VARCHAR(1024) NULL,
  transcript_status ENUM('not_started','processing','ready','failed') NOT NULL DEFAULT 'not_started',
  transcript_ref VARCHAR(255) NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_interviews_interview_no (interview_no),
  KEY idx_interviews_candidate_start (candidate_id, scheduled_start_at),
  KEY idx_interviews_position_status (position_id, status),
  KEY idx_interviews_status_start (status, scheduled_start_at),
  KEY idx_interviews_round_no (round_no),
  KEY idx_interviews_transcript_status (transcript_status),
  KEY idx_interviews_created_by (created_by),
  KEY idx_interviews_updated_by (updated_by),
  CONSTRAINT fk_interviews_candidate_id FOREIGN KEY (candidate_id) REFERENCES candidates(id),
  CONSTRAINT fk_interviews_position_id FOREIGN KEY (position_id) REFERENCES positions(id),
  CONSTRAINT fk_interviews_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  CONSTRAINT fk_interviews_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS interview_panelists (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  interview_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  panel_role ENUM('owner','co_interviewer','observer') NOT NULL DEFAULT 'co_interviewer',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_interview_panelists_interview_user (interview_id, user_id),
  KEY idx_interview_panelists_user_interview (user_id, interview_id),
  KEY idx_interview_panelists_panel_role (panel_role),
  CONSTRAINT fk_interview_panelists_interview_id FOREIGN KEY (interview_id) REFERENCES interviews(id),
  CONSTRAINT fk_interview_panelists_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS interview_scores (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  interview_id BIGINT UNSIGNED NOT NULL,
  interviewer_id BIGINT UNSIGNED NOT NULL,
  overall_score DECIMAL(5,2) NOT NULL,
  recommendation ENUM('strong_hire','hire','hold','no_hire','strong_no_hire') NOT NULL,
  scoring_payload JSON NULL,
  comment_text TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_interview_scores_interview_interviewer (interview_id, interviewer_id),
  KEY idx_interview_scores_recommendation (recommendation),
  KEY idx_interview_scores_created_at (created_at),
  KEY idx_interview_scores_interviewer_id (interviewer_id),
  CONSTRAINT fk_interview_scores_interview_id FOREIGN KEY (interview_id) REFERENCES interviews(id),
  CONSTRAINT fk_interview_scores_interviewer_id FOREIGN KEY (interviewer_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS interview_reports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  interview_id BIGINT UNSIGNED NOT NULL,
  summary_text MEDIUMTEXT NULL,
  strengths TEXT NULL,
  weaknesses TEXT NULL,
  risk_notes TEXT NULL,
  hire_recommendation ENUM('strong_hire','hire','hold','no_hire','strong_no_hire') NULL,
  report_payload JSON NULL,
  generated_by ENUM('ai','human') NOT NULL DEFAULT 'ai',
  generated_user_id BIGINT UNSIGNED NULL,
  generated_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_interview_reports_interview_id (interview_id),
  KEY idx_interview_reports_generated_at (generated_at),
  KEY idx_interview_reports_hire_recommendation (hire_recommendation),
  KEY idx_interview_reports_generated_by (generated_by),
  KEY idx_interview_reports_generated_user_id (generated_user_id),
  CONSTRAINT fk_interview_reports_interview_id FOREIGN KEY (interview_id) REFERENCES interviews(id),
  CONSTRAINT fk_interview_reports_generated_user_id FOREIGN KEY (generated_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  actor_user_id BIGINT UNSIGNED NULL,
  entity_type ENUM('candidate','resume','position','interview','score','report','user','system') NOT NULL,
  entity_id BIGINT UNSIGNED NULL,
  action VARCHAR(64) NOT NULL,
  before_data JSON NULL,
  after_data JSON NULL,
  ip_address VARCHAR(45) NULL,
  user_agent VARCHAR(512) NULL,
  trace_id VARCHAR(64) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_audit_logs_entity (entity_type, entity_id, created_at),
  KEY idx_audit_logs_actor_created_at (actor_user_id, created_at),
  KEY idx_audit_logs_action_created_at (action, created_at),
  KEY idx_audit_logs_trace_id (trace_id),
  CONSTRAINT fk_audit_logs_actor_user_id FOREIGN KEY (actor_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
